# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env:
  FLAG_SHOW_OUTPUT: false

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
  
    runs-on: ununtu-latest
    
    steps:
    - name: test01
      run: |
        date
        exit 1
    
    
  build:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: custom
      run: exit
      
    - name: Build with Maven      
      run: mvn -B package --file my-app/pom.xml
    
    - name: Display results
      if: ${{ env.FLAG_SHOW_OUTPUT }} != 'true'
      run: java -jar my-app/target/my-app-1.0-SNAPSHOT.jar
      
      
  Packaging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Packaging      
      run: |
           mvn --file my-app/pom.xml --batch-mode --update-snapshots verify
           mkdir staging && cp my-app/target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging

    - name: Show file structure
      run: |
        ls -Rl my-app/target
