# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env:
  flag_show_output: false

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file my-app/pom.xml
    
    - name: Display results
      run: |
        java -jar my-app/target/my-app-1.0-SNAPSHOT.jar
      if: ${{ env.flag_show_output }}
      
    - name: Packaging
      run: mvn --batch-mode --update-snapshots verify
           mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging

    - name: Show file structure
      run: |
        ls -Rl my-app/target
