# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env:
  FLAG_SHOW_OUTPUT: 0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_playground:
    runs-on: ubuntu-latest

    steps:
    - name: test01
      working-directory: /tmp
      run: |
        date
        pwd
        echo "ziGuy test"
        exit 1
    
    
  build:
    needs: [my_playground]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8' # doesn't work with later versions
        distribution: 'adopt'
          
    - name: Build with Maven      
      run: mvn -B package --file my-app/pom.xml
    
    - name: Display results
      if: ${{ env.FLAG_SHOW_OUTPUT == 1 }}
      run: java -jar my-app/target/my-app-1.0-SNAPSHOT.jar
    
    - run: ls -Rl my-app/target
    # - cd my-app/target
    - name: Verifying
      # run:
      #   working-directory: my-app/target
      #   mvn --batch-mode --update-snapshots verify
    - name: Packaging
      run: mkdir staging && cp my-app/target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging

      
  # Packaging:     
  #   needs: [build]
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-java@v2
  #     with:
  #       java-version: '8' # doesn't work with later versions
  #       distribution: 'adopt'
  #   - name: Show file structure
  #     run: ls -Rl my-app/target
  #   - run: mvn --batch-mode --update-snapshots verify
  #   - run: mkdir staging && cp my-app/target/*.jar staging
  #   - uses: actions/upload-artifact@v2
  #     with:
  #       name: Package
  #       path: staging



  # Packaging:     
  #   needs: [build]
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Packaging      
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: Package
  #       path: staging
  #       run: |
  #            mvn --file my-app/pom.xml --batch-mode --update-snapshots verify
  #            mkdir staging && cp my-app/target/*.jar staging

  #   - name: Show file structure
  #     run: |
  #       ls -Rl my-app/target
